//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuckyTrader_CltForm.LTService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stock", Namespace="http://schemas.datacontract.org/2004/07/LuckyTraderLib")]
    [System.SerializableAttribute()]
    public partial class Stock : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LTService.ILuckyTrader")]
    public interface ILuckyTrader {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILuckyTrader/DoRegister", ReplyAction="http://tempuri.org/ILuckyTrader/DoRegisterResponse")]
        int DoRegister(string UN, string PW, string Mail, string FN, string LN, System.DateTime Birth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILuckyTrader/DoRegister", ReplyAction="http://tempuri.org/ILuckyTrader/DoRegisterResponse")]
        System.Threading.Tasks.Task<int> DoRegisterAsync(string UN, string PW, string Mail, string FN, string LN, System.DateTime Birth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILuckyTrader/DoLogin", ReplyAction="http://tempuri.org/ILuckyTrader/DoLoginResponse")]
        int DoLogin(string UN, string PW);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILuckyTrader/DoLogin", ReplyAction="http://tempuri.org/ILuckyTrader/DoLoginResponse")]
        System.Threading.Tasks.Task<int> DoLoginAsync(string UN, string PW);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILuckyTrader/DoLogout", ReplyAction="http://tempuri.org/ILuckyTrader/DoLogoutResponse")]
        void DoLogout(int LogID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILuckyTrader/DoLogout", ReplyAction="http://tempuri.org/ILuckyTrader/DoLogoutResponse")]
        System.Threading.Tasks.Task DoLogoutAsync(int LogID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILuckyTrader/CheckStock", ReplyAction="http://tempuri.org/ILuckyTrader/CheckStockResponse")]
        LuckyTrader_CltForm.LTService.Stock[] CheckStock();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILuckyTrader/CheckStock", ReplyAction="http://tempuri.org/ILuckyTrader/CheckStockResponse")]
        System.Threading.Tasks.Task<LuckyTrader_CltForm.LTService.Stock[]> CheckStockAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILuckyTraderChannel : LuckyTrader_CltForm.LTService.ILuckyTrader, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LuckyTraderClient : System.ServiceModel.ClientBase<LuckyTrader_CltForm.LTService.ILuckyTrader>, LuckyTrader_CltForm.LTService.ILuckyTrader {
        
        public LuckyTraderClient() {
        }
        
        public LuckyTraderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LuckyTraderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LuckyTraderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LuckyTraderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int DoRegister(string UN, string PW, string Mail, string FN, string LN, System.DateTime Birth) {
            return base.Channel.DoRegister(UN, PW, Mail, FN, LN, Birth);
        }
        
        public System.Threading.Tasks.Task<int> DoRegisterAsync(string UN, string PW, string Mail, string FN, string LN, System.DateTime Birth) {
            return base.Channel.DoRegisterAsync(UN, PW, Mail, FN, LN, Birth);
        }
        
        public int DoLogin(string UN, string PW) {
            return base.Channel.DoLogin(UN, PW);
        }
        
        public System.Threading.Tasks.Task<int> DoLoginAsync(string UN, string PW) {
            return base.Channel.DoLoginAsync(UN, PW);
        }
        
        public void DoLogout(int LogID) {
            base.Channel.DoLogout(LogID);
        }
        
        public System.Threading.Tasks.Task DoLogoutAsync(int LogID) {
            return base.Channel.DoLogoutAsync(LogID);
        }
        
        public LuckyTrader_CltForm.LTService.Stock[] CheckStock() {
            return base.Channel.CheckStock();
        }
        
        public System.Threading.Tasks.Task<LuckyTrader_CltForm.LTService.Stock[]> CheckStockAsync() {
            return base.Channel.CheckStockAsync();
        }
    }
}
